#!/bin/bash

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    echo "usage: $0 STUDENT_CODE [OFFSET DAYS]"
    exit 0
fi

STUDENT_CODE=$1
OFFSET=$2

TRANSLATIONS='
T["Funkcionālā programmēšana "]                 = "Functional Programming"
T["Statistisko datu datorapstrādes metodes"]    = "Descriptive Statistics"
T["Datortīkli"]                                 = "Computer Networks"
T["Diskrētā matemātika KD"]                     = "Discrete Mathematics CW"
T["Optimizācijas  metodes"]                     = "Optimization Methods"
T["Programmatūras konstruēšanas tehnoloģija"]   = "Software Engineering"

T["Kompilatoru projektēšana"]                   = "Compiler Construction"
T["Datorgrafikas algoritmiskie līdzekļi"]       = "Computer Graphics"
T["Skaitliskās metodes"]                        = "Numerical Methods"
T["Web-aplikāciju izstrādāšanas līdzekļi"]      = "Web App Dev Tools"
T["Programmatūras izstrādes projektu vadība"]   = "Software Project Management"

T["Ievads intelektuālās sistēmās"]              = "Intelligent Systems Intro"
T["Java aplikācijas izstrāde"]                  = "Java Application Development"
T["Datortīklu drošība"]                         = "Computer Network Security"
'

if [ -n "$OFFSET" ]; then
    STR_OFFSET="&offset=$OFFSET"
fi

curl --silent "http://m.tsi.lv/schedule/?login=st$STUDENT_CODE$STR_OFFSET" | \
    sed -n -E -e '/<table/,/<\/table>/p' | \
    sed -n -E -e 's/^.*<b>([[:digit:]]+:[[:digit:]]+ [A|P]M).*<td align="center" valign="middle">([[:digit:]]+|[I]+)<\/td>.*<td align="center" valign="middle" rowspan="2">(.+)<\/td>.*$/\1\t\2\t\3/p' | \
    awk -F "\t" 'BEGIN { OFS=FS }{("date --date=\""$1"\" +%R") | getline $1; print }' | \
    awk -F "\t" "BEGIN { $TRANSLATIONS } { printf \"%-5s %8s %32s\n\", \$1, \$2, \$3 in T ? T[\$3] : \$3 }"

